### ISSUE TITLE
A NullPointerException while doing the quick and dirty way.

### ISSUE THREAD

**Issue by metacritical** [bhauman/rebel-readline#109]
>> clojure -Sdeps "{:deps {rebel-readline {:mvn/version \"0.1.0-SNAPSHOT\"}}}" -m rebel-readline.main

Exception in thread "main" java.lang.NullPointerException
        at org.jline.keymap.KeyMap.bind(KeyMap.java:372)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
        at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
        at rebel_readline.jline_api$bind_key.invokeStatic(jline_api.clj:125)
        at rebel_readline.jline_api$bind_key.invoke(jline_api.clj:124)
        at rebel_readline.clojure.widgets$clojure_emacs_mode.invokeStatic(widgets.clj:462)
        at rebel_readline.clojure.widgets$clojure_emacs_mode.invoke(widgets.clj:457)
        at rebel_readline.clojure.widgets$add_clojure_emacs_key_map.invokeStatic(widgets.clj:479)
        at rebel_readline.clojure.widgets$add_clojure_emacs_key_map.invoke(widgets.clj:476)
        at rebel_readline.clojure.widgets$add_default_widgets_and_bindings$fn__4501.invoke(widgets.clj:496)
        at rebel_readline.clojure.widgets$add_default_widgets_and_bindings.invokeStatic(widgets.clj:495)
        at rebel_readline.clojure.widgets$add_default_widgets_and_bindings.invoke(widgets.clj:494)
        at rebel_readline.line_reader$line_reader_STAR_.invokeStatic(line_reader.clj:261)
        at rebel_readline.line_reader$line_reader_STAR_.doInvoke(line_reader.clj:255)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at rebel_readline.core$line_reader.invokeStatic(core.clj:67)
        at rebel_readline.core$line_reader.doInvoke(core.clj:25)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at rebel_readline.main$_main.invokeStatic(main.clj:11)
        at rebel_readline.main$_main.doInvoke(main.clj:10)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.lang.Var.applyTo(Var.java:702)
        at clojure.core$apply.invokeStatic(core.clj:657)
        at clojure.main$main_opt.invokeStatic(main.clj:317)
        at clojure.main$main_opt.invoke(main.clj:313)
        at clojure.main$main.invokeStatic(main.clj:424)
        at clojure.main$main.doInvoke(main.clj:387)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:702)
        at clojure.main.main(main.java:37)

**Comment by bhauman** [comment]
I could use some more info:



In the following XML file there is a <scm> entry and i need the git commit which is in the <tag>
~/.m2/repository/rebel-readline/rebel-readline/0.1.0-SNAPSHOT/rebel-readline-0.1.0-SNAPSHOT.pom

What platform are you on? and which version of Java?

**Comment by bhauman** [comment]
I found the problem, it seems that your terminal or platform doesn't support home or end key.

**Comment by bhauman** [comment]
It'd be great to know which terminal and platform you are using.

**Comment by bhauman** [comment]
pushed a fix to 0.1.0-SNAPSHOT

**Comment by metacritical** [comment]
I was using the mac default terminal. But after your new push this new update works. Thanks!
