### ISSUE TITLE
Exception when running on urxvt

### ISSUE THREAD

**Issue by JoelSanchez** [bhauman/rebel-readline#137]
Running this on urxvt:
```
clojure -Sdeps "{:deps {com.bhauman/rebel-readline {:mvn/version \"0.1.1\"}}}" -m rebel-readline.main
```
Results in:
```
Exception in thread "main" java.lang.NumberFormatException: For input string: "default", compiling:(line_reader.clj:50:18)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3700)
	at clojure.lang.Compiler$StaticMethodExpr.eval(Compiler.java:1721)
	at clojure.lang.Compiler$IfExpr.eval(Compiler.java:2720)
	at clojure.lang.Compiler$MapExpr.eval(Compiler.java:3047)
	at clojure.lang.Compiler$DefExpr.eval(Compiler.java:457)
	at clojure.lang.Compiler.eval(Compiler.java:7067)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at rebel_readline.clojure.main$eval153$loading__6434__auto____154.invoke(main.clj:1)
	at rebel_readline.clojure.main$eval153.invokeStatic(main.clj:1)
	at rebel_readline.clojure.main$eval153.invoke(main.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7051)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at rebel_readline.main$eval147$loading__6434__auto____148.invoke(main.clj:1)
	at rebel_readline.main$eval147.invokeStatic(main.clj:1)
	at rebel_readline.main$eval147.invoke(main.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7051)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.main$main_opt.invokeStatic(main.clj:317)
	at clojure.main$main_opt.invoke(main.clj:313)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: java.lang.NumberFormatException: For input string: "default"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at rebel_readline.utils$terminal_background_color_QMARK_$fn__224$fn__225.invoke(utils.clj:22)
	at clojure.core$map$fn__5587.invoke(core.clj:2745)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:528)
	at clojure.lang.RT.nthFrom(RT.java:974)
	at clojure.lang.RT.nth(RT.java:933)
	at rebel_readline.utils$terminal_background_color_QMARK_.invokeStatic(utils.clj:22)
	at rebel_readline.utils$terminal_background_color_QMARK_.invoke(utils.clj:20)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3695)
```
(It seems a problem with that "terminal-background-color!" call, looks like it expects a color but urxvt gives "default")

**Comment by JoelSanchez** [comment]
My `.Xresources` file:
```
! Solarized color scheme for the X Window System
!
! http://ethanschoonover.com/solarized


! Common

#define S_yellow        #b58900
#define S_orange        #cb4b16
#define S_red           #dc322f
#define S_magenta       #d33682
#define S_violet        #6c71c4
#define S_blue          #268bd2
#define S_cyan          #2aa198
#define S_green         #859900


! Dark

#define S_base03        #002b36
#define S_base02        #073642
#define S_base01        #586e75
#define S_base00        #657b83
#define S_base0         #839496
#define S_base1         #93a1a1
#define S_base2         #eee8d5
#define S_base3         #fdf6e3


! Light

! #define S_base03        #fdf6e3
! #define S_base02        #eee8d5
! #define S_base01        #93a1a1
! #define S_base00        #839496
! #define S_base0         #657b83
! #define S_base1         #586e75
! #define S_base2         #073642
! #define S_base3         #002b36


! To only apply colors to your terminal, for example, prefix
! the color assignment statement with its name. Example:
!
! URxvt*background:            S_base03

URxvt.background:              S_base03
URxvt.foreground:              S_base0
URxvt.fading:                  40
URxvt.fadeColor:               S_base03
URxvt.cursorColor:             S_base1
URxvt.pointerColorBackground:  S_base01
URxvt.pointerColorForeground:  S_base1

*color0:                  S_base02
*color1:                  S_red
*color2:                  S_green
*color3:                  S_yellow
*color4:                  S_blue
*color5:                  S_magenta
*color6:                  S_cyan
*color7:                  S_base2
*color9:                  S_orange
*color8:                  S_base03
*color10:                 S_base01
*color11:                 S_base00
*color12:                 S_base0
*color13:                 S_violet
*color14:                 S_base1
*color15:                 S_base3




! URxvt

! General settings
URxvt.saveLines: 2000
URxvt.scrollBar: False
URxvt.scrollstyle: rxvt
URxvt.termName: xterm-256color
URxvt.urgentOnBell: True
URxvt.cursorBlink: False
URxvt.geometry: 85x25
URxvt.iconFile:  /usr/share/icons/custom/urxvt.png
URxvt.internalBorder: 10

! Extensions
URxvt.urlLauncher: xdg-open
URxvt.urlButton: 1
URxvt.underlineURLs: True

! URxvt.copyCommand:  xclip -i -selection clipboard
! URxvt.pasteCommand: xclip -o -selection clipboard

! Keybindings
! URxvt.perl-ext-common: ...,keyboard-select,url-select,clipboard
! URxvt.keysym.Mod4-c: perl:clipboard:copy
! URxvt.keysym.Mod4-v: perl:clipboard:paste
! URxvt.keysym.Mod4-C-v: perl:clipboard:paste_escaped
! URxvt.keysym.M-c: perl:clipboard:copy
! URxvt.keysym.M-v: perl:clipboard:paste
! URxvt.keysym.M-C-v: perl:clipboard:paste_escaped
! URxvt.keysym.M-Escape: perl:keyboard-select:activate
! URxvt.keysym.C-Escape: perl:keyboard-select:activate
! URxvt.keysym.M-u: perl:url-select:select_next

! Fonts

!Inconsolata
URxvt.hintstyle: hintnone
URxvt.font: xft:Inconsolata:size=12:antialias=true:style=Regular
URxvt.boldFont: xft:Inconsolata:size=12:antialias=true
URxvt.imFont: xft:Inconsolata:size=12:antialias=true
URxvt.italicFont: xft:Inconsolata:size=12:antialias=true
URxvt.boldItalicFont: xft:Inconsolata:size=12:antialias=true
URxvt.letterSpace: -1


! Tango theme

!URxvt.background: #1C1C1C
!URxvt.foreground: #DEDEDE

! man colors

URxvt.colorIT:      #87af5f
URxvt.colorBD:      #d7d7d7
URxvt.colorUL:      #87afd7

! Cursor theme
Xcursor.theme:DMZ-White
```

**Comment by JoelSanchez** [comment]
I see you added a "help-wanted" tag. I can give it a try this weekend.

**Comment by bhauman** [comment]
Great :)

**Comment by JoelSanchez** [comment]
#140 merged
